#
# Copyright 2017 Freescale Semiconductor
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += imx8mq_maaxboard.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += ddr4_timing.o
endif

obj-y += ../../freescale/common/mmc.o
